Updated Firefox Dark
RaitaroH/YouTube-DeepDark pull request #63
Opened 2021-08-12 07:03 UTC by MaximeRF

Hey @RaitaroH , I've updated the Firefox Dark colors to really match Firefox's Dark theme. I think it's much better but that's just my opinion, feel free to ignore this PR.

2021-08-19 09:36 UTC, RaitaroH commented
Right, so the new "dark" colors are inline with Firefox 91. I did a bit of tweaking:

```css
		else if stylus-deepdark-style == "Firefox-Dark91" {
			--main-color: #00ddff;
			--main-background: #1c1b22;
			--second-background: #23222b;
			--hover-background: #2b2a33;
			--main-text: #fbfbfe;
			--dimmer-text: #b8b7bb;
			--shadow: 0 1px 0.5px rgba(0, 0, 0, .13);
		}
```
I also think this is a bit closer to what I get for Afterglow:
```css
		else if stylus-deepdark-style == "Firefox-Alpenglow-Dark" {
			--main-color: #C488FC;
			--main-background: #21133d;
			--second-background: #2a1e52;
			--hover-background: #2d245b;
			--main-text: #ffffff;
			--dimmer-text: #E3DBFA;
			--shadow: 0 1px .5px rgba(35, 22, 65, .5);
		}
```

2021-08-22 12:11 UTC, vednoc requested changes

2021-08-22 12:11 UTC, vednoc commented on YouTubeDeepDarkMaterial.user.css
> +			--second-background: #0e0d11;
Swap colors around, so that highlights can have lighter colors than the background.

2021-08-22 12:11 UTC, vednoc commented on YouTubeDeepDarkMaterial.user.css
> +			--second-background: #231641;
Same as my previous comment.

2021-08-24 09:56 UTC, closed without merging